### ISSUE TITLE
Drone Response

### ISSUE THREAD

**Issue by marcuusmelo** [dbaldwin/DroneBlocks-TelloEDU-Python#1]
The commands work but I don't receive the drone response. For example, if I try to check the battery level I don't receive the information

**Comment by dbaldwin** [comment]
Hi @marcuusmelo are you running the latest Tello firmware? Also, have you checked that you get a response in Packet Sender to rule out any potential issues with your Python code?

**Comment by marcuusmelo** [comment]
Let me change my question:
Looks like the code only gets the response from drone 1, right? For example, if you send commands to check the battery for both drones, you are only going to get response from drone 1

**Comment by dbaldwin** [comment]
Good point. Try this update. It should do the trick:

https://github.com/dbaldwin/DroneBlocks-TelloEDU-Python/commit/03691896dfe271b57b9ec0528ecd7af0a9a92280

I tested it with the battery command and received responses from both Tello EDUs. I also ran the box mission and received responses from both.

**Comment by marcuusmelo** [comment]
Thanks for it!
